import type { Metadata } from "next";
import { Inter, Caveat, Orbitron, Oxanium } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});

const oxanium = Oxanium({
  subsets: ["latin"],
  variable: "--font-oxanium",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${caveat.variable} ${orbitron.variable} ${oxanium.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
